name: CI
on: [push]

jobs:
  build:
    name: Contract compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.18
        uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - name: Start node
        uses: JarvusInnovations/background-action@v1
        with:
          run: echo "Testing node..."

          wait-on: http://localhost:8011

          wait-for: 5m

      - name: Compile and deploy ExecutionHelper.
        run:  make compile-and-deploy-execution-helper 
