name: CI
on: [push]

jobs:
  build:
    name: Contract compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.18
        uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - name: Initial setup and start node
        run: |
          git clone https://github.com/matter-labs/era-test-node.git
          make setup run-era-test-node

      - name: Compile and deploy ExecutionHelper.
        run:  make compile-and-deploy-execution-helper 
