name: CI
on: [push]

jobs:
  build:
    name: Contract compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.18
        uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - name: Setup test-node 
        run: |
	        curl -LO https://github.com/matter-labs/era-test-node/releases/download/v0.1.0-alpha.10/era_test_node-v0.1.0-alpha.10-x86_64-unknown-linux-gnu.tar.gz
          tar -zxvf era_test_node-v0.1.0-alpha.10-x86_64-unknown-linux-gnu.tar.gz
          chmod +x ./era_test_node
          ./era_test_node run &

      - name: Check server has started
        run: |
				 sleep 10 && curl --request POST \
										--url http://localhost:8011/ \
										--header 'content-type: application/json' \
										--data '{ "jsonrpc": "2.0", "id": "1", "method": "eth_chainId", "params": []}'

      - name: Setup project dependencies 
        run: |
          yarn global add node-gyp && yarn install

      - name: Compile and deploy ExecutionHelper.
        run: |
          cd ExecutionHelper
          yarn install
          yarn hardhat compile
          yarn hardhat deploy-zksync --script deploy.ts --network inMemoryNode
          
