name: CI
on: [push]

jobs:
  build:
    name: Contract compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.18
        uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - name: Install dependencies
        run: yarn install

      - name: Compile and deploy ExecutionHelper.
        run: |
          yarn install
          cd ExecutionHelper
          echo $(pwd)
          yarn install
          yarn run hardhat compile
          yarn run hardhat deploy-zksync --script deploy.ts
