name: CI
on: [push]

jobs:
  build:
    name: Contract compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.18
        uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - name: Run Era Test Node
        uses: dutterbutter/era-test-node-action@latest

      - name: Check server has started
        run: |
         sleep 10 && curl --request POST \
                    --url http://localhost:8011/ \
                    --header 'content-type: application/json' \
                    --data '{ "jsonrpc": "2.0", "id": "1", "method": "eth_chainId", "params": []}'

      - name: Setup project dependencies 
        run: |
          yarn global add node-gyp && yarn install

      - name: Compile and deploy ExecutionHelper.
        working-directory: ./ExecutionHelper
        run: |
          yarn install
          yarn hardhat compile
          yarn hardhat deploy-zksync --script deploy.ts --network inMemoryNode
          
