name: CI
on: [push]

jobs:
  build:
    name: Contract compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.18
        uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - name: Run Era Test Node
        uses: dutterbutter/era-test-node-action@latest

      - name: Assert that era-test-node is running
        run: |
          curl http://localhost:8011/ \
            -X POST \
            -H "Content-Type: application/json" \
            --data '{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}'

      - name: Setup project dependencies 
        run: |
          yarn global add node-gyp@10.0.1 && yarn install

      - name: Compile and deploy ExecutionHelper.
        working-directory: ./ExecutionHelper
        run: |
          yarn install
          yarn hardhat compile
          yarn hardhat deploy-zksync --script deploy.ts --network inMemoryNode
          
