name: CI
on: [push]

jobs:
  build:
    name: Contract compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.18
        uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - name: Start node
        uses: JarvusInnovations/background-action@v1
        with:
          run: curl -LO https://github.com/matter-labs/era-test-node/releases/download/v0.1.0-alpha.10/era_test_node-v0.1.0-alpha.10-x86_64-unknown-linux-gnu.tar.gz

          wait-on: http://localhost:8011

          wait-for: 5m

      - name: Compile and deploy ExecutionHelper.
        run:  make compile-and-deploy-execution-helper 
